apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ns-admin
  namespace: dev
subjects:
- kind: User
  name: system:serviceaccounts:dev:jane
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: admin
  apiGroup: rbac.authorization.k8s.io
---  
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ns-view
  namespace: dev
subjects:
- kind: User
  name: system:serviceaccounts:dev:ken
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name:  view
  apiGroup: rbac.authorization.k8s.io