apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: all-pors-reading
subjects:
- kind: Group
  name: system:serviceaccounts:promethus
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: all-pors-reading
  apiGroup: rbac.authorization.k8s.io